### PR TITLE
make web application an optional Cosmos extra

### PR DESCRIPTION
**Pull request by ahvigil**
Taking a stab at an implementation for #108. Just pushing all the imports from flask into `try: ... except ImportError:` blocks and raising `NotImplementedError`s when flask is not present. Running the web ui should now require `pip install cosmos[web]`.

I imagine this also might require a mention in the docs and some testing.

### CODE REVIEW

**Comment by egafni** [comment]
Hey there, I just saw this.  Are you still interested in this being merged?

**Comment by egafni** [comment]
ping @ahvigil

**Comment by egafni** [comment]
I'm happy to merge but there are conflicts now :(
could you please resolve?

**Comment by ahvigil** [comment]
sorry just had time to revisit this now. Merged conflicts and did the following to test this works:

1) run unit tests, verify examples pass
```
========================================================== test session starts ===========================================================
platform darwin -- Python 2.7.15, pytest-4.4.0, py-1.7.0, pluggy-0.9.0
rootdir: /Users/avigil/Desktop/COSMOS2
plugins: metadata-1.7.0, html-1.19.0, celery-4.2.1
collected 5 items                                                                                                                        

test/test_edge_cases.py .                                                                                                          [ 20%]
test/test_examples.py ....                                                                                                         [100%]

============================================================ warnings summary ============================================================
test/test_edge_cases.py::test_zero_tasks
  /Users/avigil/.virtualenvs/pipe/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:1466: SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
    default.DefaultDialect.__init__(self, **kwargs)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================== 5 passed, 1 warnings in 8.88 seconds ==================================================
```
2) pip install and verify flask is not present, running web command prints error:
```
$ pip freeze | grep flask 
$ cosmos runweb --host 0.0.0.0 --port 12345 sqlite:///examples/sqlite.db
Traceback (most recent call last):
  File "/Users/avigil/.virtualenvs/pipe/bin/cosmos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/avigil/Desktop/COSMOS2/bin/cosmos", line 136, in <module>
    globals()[cmd](**kwargs)
  File "/Users/avigil/Desktop/COSMOS2/bin/cosmos", line 32, in runweb
    cosmos_app.runweb(host, port)
  File "/Users/avigil/Desktop/COSMOS2/cosmos/models/Cosmos.py", line 301, in runweb
    self.init_flask()
  File "/Users/avigil/Desktop/COSMOS2/cosmos/models/Cosmos.py", line 290, in init_flask
    from cosmos.web.views import gen_bprint
  File "/Users/avigil/Desktop/COSMOS2/cosmos/web/__init__.py", line 4, in <module>
    raise NotImplementedError("please install the [web] extra for web functionality")
NotImplementedError: please install the [web] extra for web functionality
```
3) pip install with web extra and verify web command  now runs
```
cosmos runweb --host 0.0.0.0 --port 12345 sqlite:///examples/sqlite.db
 * Serving Flask app "cosmos.models.Cosmos" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:12345/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
127.0.0.1 - - [23/Dec/2019 11:59:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Dec/2019 11:59:42] "GET /cosmos/static/bootstrap3/datatables/assets/css/datatables.css HTTP/1.1" 404 -
```

**Comment by ahvigil** [comment]
added a short comment in the installation docs, this should be ready to go!

**Comment by egafni** [comment]
Please feel free to e-mail me if I am unresponsive.  I am not sure if I am getting the proper notifications.

Thanks though!  Will merge

**Pull request merged**
